### ISSUE TITLE
PECNet+NPSN on SDD

### ISSUE THREAD

**Issue by WBMao** [InhwanBae/NPSN#1]
Hi,
Thanks for the nice work, I have a question regarding reproducing the numbers in Table 1 on SDD with PECNet+NPSN, which is `8.56/11.85` on minADE/minFDE.

Do you have the pretrained models, and also the training pipeline?

Thanks in advance!

**Comment by InhwanBae** [comment]
Hi @WBMao,

To train NPSN-PECNet on the SDD dataset, I used the official code of [PECNet](https://github.com/HarshayuGirase/Human-Path-Prediction/tree/master/PECNet) (model, dataloader, etc). The only different part is the forward function of the model, and I modified the PECNet so that the random latent vector can be input from the outside.
```python
def forward(self, x, initial_pos, dest = None, mask = None, device=torch.device('cpu'), noise=None):
#...
    if not self.training:
        if noise is not None:
            z = noise * self.sigma
        else:
            z = torch.Tensor(x.size(0), self.zdim)
            z.normal_(0, self.sigma)
    else:
#...
```
Also, the training pipeline is almost the same as in this repository. I will clean up and upload the NPSN-PECNet code in a few days.

**Comment by InhwanBae** [comment]
Hi @WBMao! I've just uploaded the train/test code for PECNet. Please check [important notes for PECNet](https://github.com/InhwanBae/NPSN#pretrained-models). The NPSN-PECNet codes for the SDD dataset are in the [`./baselines/pecnet/pecnet-dataloader/`](https://github.com/InhwanBae/NPSN/tree/main/baselines/pecnet/pecnet_dataloader) folder.

If you evaluate NPSN-PECNet using pre-trained weights, you should get the same values reported in our paper. If you train the model yourself, you can get `11.85` at epoch 61, and better results at 90 epoch. (`ADE: 8.55, FDE: 11.67, TCC: 0.667`)

I'm closing this issue for now. Please feel free to open another issue for other questions.
