### ISSUE TITLE
Reproducing the results from the rest of the models and datasets

### ISSUE THREAD

**Issue by novinsh** [InhwanBae/NPSN#4]
Could you please provide details on reproducing the results for the rest of the models and datasets?
Is there any particular reason you did not provide code for the other baselines and datasets?

**Comment by InhwanBae** [comment]
Hi @novinsh,

Thank you for showing interest in my paper. The reason I've only uploaded a few models to this repo is that other models and datasets adopt their own dataloaders/training methods. Sadly, this resulted in highly fragmented code, and to fill out Table 1 in our paper, there were as many as 16 project folders when I wrote the paper. Due to many emails and requests, I've updated the PECNet baseline, but the code has become overly complex. As more baselines are added, it will become even more complicated, so I've prioritized making it public for SOTA models and famous datasets.

Fortunately, our QMC and NPSN approaches are very intuitive and straightforward (1GAT+3MLP), so I believe they can be simply applied to each baseline model. As a fundamental solution, I plan to rebase the repo by creating separate trainers for each baseline and combining them into one code, but it will take quite a while. Please request via email if needed.

**Comment by InhwanBae** [comment]
I'm closing this issue for now. Please request via email if you need code for other older baselines, such as Social-GAN, and feel free to open another issue for other questions.
